export enum ClusterSteps {
  COMPILE = 'Compile',
  DEPLOYED = 'Deployed',
  CREATING = 'Creating',
  ADDED = 'Added',
  ACTIVE = 'Active',
  INSTALL = 'Installation',
  UNINSTALL = 'Uninstall',
  CREETENAMESPACE = 'CreeteNamespace',
  INSTALLKUBELESS = 'InstallKubeless',
  INSTALLCERTMANAGER = 'InstallCertManager',
  INSTALLMETRICSSERVER = 'InstallMetricsServer',
  ADDCERTCLUSTERISSUER = 'AddCertClusterIssuer',
  INSTALLKONG = 'InstallKong',
  INSTALLPROMETHEUS = 'InstallPrometheus',
  REMOVING = 'Removing',
  STOP = 'Stopping',
  CHECKLOADBALANCERS = 'CheckLoadBalancers',
  INSTALLINGRESS = 'InstallIngress',
  DELETENAMESPACE = 'DeleteNamespace',
  UNINSTALLKUBELESS = 'UninstallKubeless',
  UNINSTALLCERTMANAGER = 'UninstallCertManager',
  UNINSTALLCERTCLUSTERISSUER = 'UninstallCertClusterIssuer',
  UNINSTALLKONG = 'UninstallKong',
  UNINSTALLPROMETHEUS = 'UninstallPrometheus',
  UNINSTALLINGRESS = 'UninstallIngress',

}
